enableSearch = true
colorscheme = "blowfish"  
enableStructuredBreadcrumbs = true
smartTOC = true

[seo]
  description = "Portfolio technique, robotique, électronique, Intelligence artificielle, impression 3D"
  keywords = ["robotique", "électronique", "ROS 2", "Intelligence artificielle", "impression 3D"]
  robots = "index, follow"

[author]
  name = "Louis St-Hilaire"
  headline = "Robotique, électronique et intelligence artificielle"

[homepage]
  layout = "page"
  showRecent = false

[list]
  showCards = true
  showSummary = true
  groupByYear = false

[seo.schema]
  type = "Person"

[header]
  layout = "fixed"
  showTitle = false
  showLanguageSwitcher = false

[footer]
  showCopyright = false
  showThemeAttribution = false

[article]
  showDate = false
  showDateUpdated = true
  showAuthor = false
  showBreadcrumbs = true
  showReadingTime = false
  showTableOfContents = false
  showWordCount = false
  showCopyright = false
